services:
  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j_local
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password # Format: <username>/<password>
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./jqassistant/store/data:/data # Mount onto generated data
