name: Build Docker Image

on:
  push:
    branches:
      - feat/build-on-push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up multi-platform builder
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - name: Get short commit hash for Docker tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --target nemesis \
            --platform ${{ matrix.architecture }} \
            --build-arg BUILDPLATFORM=${{ matrix.architecture }} \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ env.TAG }} \
            --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest \
            --push .
